/*
 * File: app/store/Tweets.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GNApp.store.medias', {
    extend: 'Ext.data.Store',
    requires: [
        'GNApp.model.media'
    ],

    config: {
        autoLoad: true,
        model: 'GNApp.model.media',
        storeId: 'medias',
        proxy: {
            type: 'jsonp',
            url: 'http://gntestserver.appspot.com/pokeList.jsp',
            callbackKey: 'GNCallBack',
            
            reader: {
                type: 'json'
            }
        }
    }
});