/*
 * File: app/store/Tweets.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GNApp.store.sharePeoples', {
    extend: 'Ext.data.Store',
    requires: [
        'GNApp.model.GuestBook'
    ],

    config: {
        autoLoad: true,
        model: 'GNApp.model.GuestBook',
        storeId: 'Id_GuestBook',
        data: [
				{ 
					"text": "기부합시다1", 
					"created_at": "2012-01-01", 
					"name": "한인규",
				},
				
				{ 
					"text": "기부합시다2", 
					"created_at": "2012-01-02", 
					"name": "임상학",
				},
				
				{ 
					"text": "기부합시다3", 
					"created_at": "2012-01-03", 
					"name": "전병수",
				},
				
				{ 
					"text": "기부합시다4", 
					"created_at": "2012-01-04", 
					"name": "피오니",
				}
			]

    }
});