/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GNApp.controller.Main', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            mainView: '#MainView',
            toolBar: '#TweetToolbar',
            tweetData: '#TweetData',
            backButton: '#Back',
            tweetPreview: '#TweetPreview'
        },

        control: {
            "[action=back]": {
                tap: 'onButtonTap'
            },
            "#TweetData": {
                itemtap: 'onDataItemTap'
            }
        }
    },

    onButtonTap: function(button, e, options) {
        button.hide();
        
        this.getToolBar().setTitle('Gallery');
        
        this.getMainView().animateActiveItem(0, { type: "slide",  direction: "right" });

        this.getTweetData().deselectAll();

    },
    // dataview(Thumbnail) image itemtap event
    onDataItemTap: function(dataview, index, target, record, e, options) {
        this.getMainView().animateActiveItem(1, { type: "slide", direction: "left" });
        
        this.getBackButton().show();
        
        /* index to each image */
    	this.getTweetPreview().setActiveItem(index);
    	// carousel 의 상태를 숫자로
        this.getToolBar().setActiveItem(index);

        this.getToolBar().setTitle('<div>' + record.get('name') + '</div>'); /* each Carousel Title */

    }
});