/*
 * File: app/model/Tweet.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GNApp.model.Tweet', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
            {
            	name:'id',
            	type:'auto'
            },
            {
                name: 'text',
                type: 'string'
            },
            {
                name: 'created_at',
                type: 'date'
            },
            {
                mapping: 'user.profile_image_url',
                name: 'profile_image_url',
                type: 'auto'
            },
            {
                mapping: 'user.description',
                name: 'description',
                type: 'string'
            },
            {
                mapping: 'user.name',
                name: 'name',
                type: 'string'
            }
        ]
    }
});